"""create messages and chat tables

Revision ID: 4e251a4eb518
Revises: 0510596dd4f0
Create Date: 2025-09-03 18:53:13.639161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e251a4eb518'
down_revision: Union[str, None] = '0510596dd4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messesges_id', table_name='messesges')
    op.drop_table('messesges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messesges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='messesges_pkey')
    )
    op.create_index('ix_messesges_id', 'messesges', ['id'], unique=False)
    # ### end Alembic commands ###
